export const environment = {
  SENTRY_ENVIRONMENT: 'production',
  SENTRY_DSN: '',
  SENTRY_RELEASE: '',
  ENABLE_SENTRY: false,
  DEBUG_MODE: true,
  JIRA_RATE_LIMIT_CONFIG: 9,
  APP_VERSION: '1.9.10',
  ENABLE_POSTHOG: false,
  POSTHOG_KEY: '',
  POSTHOG_HOST: '',
  ThemeConfiguration: {
    appLogo: 'assets/img/logo/specifai_light_applogo.svg',
    appLogoDark: 'assets/img/logo/specifai_dark_applogo.svg',
    appName: 'Specifai',
    appWelcomeTitle: 'Welcome to Specifai',
    appDescription: 'Get started to accelerate SDLC Process',
    companyName: 'Presidio',
    companyLogo: 'assets/img/presidio-white.svg',
    companyLogoColor: 'assets/img/presidio-blue.svg',
    appIcons: {
      mac: 'assets/icons/mac_icon.icns',
      win: 'assets/icons/win_icon.ico',
      linux: 'assets/icons/linux_icon.png',
    },
  },
};
